<?php
if(!CModule::IncludeModule("iblock")) die('Это фиаско, братан!');
$CIBlockPropertiesHelper = new CIBlockProperty;
$arPropertiesFields = [
    ["VIN", "VIN", "S", "N"],
    ["ID", "ID", "N", "N"],
    ["URL", "URL", "S", "N"],
    ["MURL", "MURL", "S", "N"],
    ["CAR_CREATE_DATE", "ДАТА СОЗДАНИЯ АВТОМОБИЛЯ", "S", "N"],
    ["CAR_UPDATE_DATE", "ДАТА ОБНОВЛЕНИЯ АВТОМОБИЛЯ", "S", "N"],
    ["PRICE_UPDATE_DATE", "ДЕНЬ ОБНОВЛЕНИЯ ЦЕНЫ", "S", "N"],
    ["CAR_VALID_THRU_DATE", "АВТОМОБИЛЬ ДЕЙСТВИТЕЛЕН ДО", "S", "N"],
    ["MARK", "МАРКА", "S", "N"],
    ["MODEL", "МОДЕЛЬ", "S", "N"],
    ["GENERATION", "ПОКОЛЕНИЕ", "S", "N"],
    ["MODIFICATION", "МОДИФИКАЦИЯ", "S", "N"],
    ["MODIFICATION_ILSA", "MODIFICATION_ILSA", "S", "N"],
    ["MODIFICATION_CODE", "МОДИФИКАЦИОННЫЙ КОД", "S", "N"],
    ["YEAR", "ГОД", "S", "N"],
    ["EXTERIOR_COLOR", "ВНЕШНИЙ ЦВЕТ", "S", "N"],
    ["EXTERIOR_CODE", "ВНЕШНИЙ КОД", "S", "N"],
    ["BODY_TYPE", "ТИП КУЗОВА", "S", "N"],
    ["DOORS_COUNT", "КОЛИЧЕСТВО ДВЕРЕЙ", "N", "N"],
    ["DISPLACEMENT", "СМЕЩЕНИЕ", "S", "N"],
    ["ENGINE_TYPE", "ТИП ДВИГАТЕЛЯ", "S", "N"],
    ["HORSE_POWER", "ЛОШАДИНЫЕ СИЛЫ", "N", "N"],
    ["TRANSMISSION", "КОРОБКА ПЕРЕДАЧ", "S", "N"],
    ["GEAR_TYPE", "ТИП ПРИВОДА", "S", "N"],
    ["STEERING_WHEEL", "РУЛЬ", "S", "N"],
    ["STOCK", "АКЦИИ", "S", "N"],
    ["STATE", "ГОСУДАРСТВО", "S", "N"],
    ["CAR_LOCATION", "МЕСТОПОЛОЖЕНИЕ", "S", "N"],
    ["RUN", "ПРОБЕГ", "N", "N"],
    ["RUN_METRIC", "МЕТРИКА ПРОБЕГА", "S", "N"],
    ["PRICE", "ЦЕНА", "N", "N"],
    ["BASE_PRICE", "ОСНОВНАЯ ЦЕНА", "N", "N"],
    ["SALE_PRICE", "ЦЕНА ПРОДАЖИ", "N", "N"],
    ["MONTHLY_PAYMENT", "ЕЖЕМЕСЯЧНО ОПЛАТА", "N", "N"],
    ["CURRENCY_TYPE", "ТИП ВАЛЮТЫ", "S", "N"],
    ["HAGGLE", "ТОРГ", "S", "N"],
    ["CUSTOM_HOUSE_STATE", "ТАМОЖЕННЫЙ ДОМ", "S", "N"],
    ["SELLER", "ПРОДАВЕЦ", "S", "N"],
    ["SELLER_CITY", "ПРОДАВЕЦА ГОРОД", "S", "N"],
    ["SELLER_PHONE", "ПРОДАВЕЦА ТЕЛЕФОН", "S", "N"],
    ["ADDITIONAL_INFO_EXTERIOR", "ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ ЭКСТЕРЬЕР", "S", "N"],
    ["ADDITIONAL_INFO_INTERIOR", "ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ ИНТЕРЬЕР", "S", "N"],
    ["ADDITIONAL_INFO_SAFETY", "ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ БЕЗОПАСНОСТЬ", "S", "N"],
    ["ADDITIONAL_INFO_COMFORT", "ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ КОМФОРТ", "S", "N"],
    ["ADDITIONAL_INFO_WARRANTY", "ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ ГАРАНТИЯ", "S", "N"],
    ["EQUIPMENT_EXTERIOR", "ЭКСТЕРЬЕР (ОСНАЩЕНИЕ;ОБОРУДОВАНИЕ)", "S", "N"],
    ["EQUIPMENT_INTERIOR", "ИНТЕРЬЕР (ОСНАЩЕНИЕ;ОБОРУДОВАНИЕ)", "S", "N"],
    ["EQUIPMENT_SAFETY", "БЕЗОПАСНОСТЬ (ОСНАЩЕНИЕ;ОБОРУДОВАНИЕ)", "S", "N"],
    ["EQUIPMENT_COMFORT", "КОМФОРТ (ОСНАЩЕНИЕ;ОБОРУДОВАНИЕ)", "S", "N"],
    ["EQUIPMENT", "ОСНАЩЕНИЕ;ОБОРУДОВАНИЕ", "S", "Y"],
    ["IMAGE", "ИЗОБРАЖЕНИЕ", "S", "Y"],
];
foreach ($arPropertiesFields as $arPropertyFields) {
    $arFields = Array(
        "NAME" => $arPropertyFields[1],
        "ACTIVE" => "Y",
        "SORT" => "500",
        "CODE" => $arPropertyFields[0],
        "PROPERTY_TYPE" => $arPropertyFields[2],
        "IBLOCK_ID" => 1,
        "MULTIPLE" => $arPropertyFields[3]
    );
    $CIBlockPropertiesHelper->Add($arFields);
}